// apps/vue/src/User.vue
<template>
  <div :class="UserStyles()">
    <img src="https://placehold.it/72/72">
    <h1>Foo Bar</h1>
    <remove-user-button />
  </div>
</template>

<script lang="ts">
import UserStyles from "@maxmind/core/ui/User";
import RemoveUserButton from "./RemoveUserButton.vue";

export default {
  components: {
    RemoveUserButton,
  },
  data: () => ({
    UserStyles,
  }),
};
</script>

// apps/react/src/components/User.tsx
import IUser from "@maxmind/core/types/User";
import UserStyles from "@maxmind/core/ui/User";
import * as React from "react";
import RemoveUserButton from "./RemoveUserButton";

const User: React.FC<IUser> = ({
  firstName,
  lastName,
  photo,
  uuid,
}) => (
  <div className={UserStyles()}>
    <img src={photo} />
    <h1>{firstName} {lastName}</h1>
    <RemoveUserButton uuid={uuid} />
  </div>
);

export default User;
