// apps/vue/src/App.vue
<template>
  <div :class="PageStyles()">
    <div :class="ContainerStyles()">
      <add-user-button />
      <users />
    </div>
  </div>
</template>

<script lang="ts">
import ContainerStyles from "@maxmind/core/ui/Container";
import PageStyles from "@maxmind/core/ui/Page";
import AddUserButton from "./AddUserButton.vue";
import Users from "./Users.vue";

export default {
  name: 'App',
  components: {
    AddUserButton,
    Users,
  },
  data: () => ({
    ContainerStyles,
    PageStyles,
  }),
};
</script>

// apps/svelte/src/App.svelte
<script>
	import * as UI from '@maxmind/core/ui';
</script>

<div class="{UI.Page()}">
	<div class="{UI.Container()}">
		<button class="{UI.AddUserButton()}">Add User</button>
		<div class="{UI.User()}">
			<img src="https://placehold.it/72/72" alt="">
			<h1>Foo Bar</h1>
			<button class="{UI.RemoveUserButton()}">Remove User</button>
		</div>
		<div class="{UI.User()}">
			<img src="https://placehold.it/72/72" alt="">
			<h1>Foo Bar</h1>
			<button class="{UI.RemoveUserButton()}">Remove User</button>
		</div>
		<div class="{UI.User()}">
			<img src="https://placehold.it/72/72" alt="">
			<h1>Foo Bar</h1>
			<button class="{UI.RemoveUserButton()}">Remove User</button>
		</div>
		<div class="{UI.User()}">
			<img src="https://placehold.it/72/72" alt="">
			<h1>Foo Bar</h1>
			<button class="{UI.RemoveUserButton()}">Remove User</button>
		</div>
		<div class="{UI.User()}">
			<img src="https://placehold.it/72/72" alt="">
			<h1>Foo Bar</h1>
			<button class="{UI.RemoveUserButton()}">Remove User</button>
		</div>
	</div>
</div>
